# Generated by Django 4.2.13 on 2026-03-23 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_type', models.CharField(choices=[('points', 'Köpoäng'), ('first_come', 'Först till kvarn'), ('lottery', 'Lottning')], default='points', max_length=20)),
                ('require_bankid', models.BooleanField(default=True)),
                ('require_no_debt', models.BooleanField(default=True)),
                ('min_credit_score', models.FloatField(default=60.0)),
                ('min_queue_points', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_config', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Kökonfiguration',
                'verbose_name_plural': 'Kökonfigurationer',
            },
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=200)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('monthly_income_sek', models.PositiveIntegerField()),
                ('household_size', models.PositiveSmallIntegerField(default=1)),
                ('queue_points', models.PositiveIntegerField(default=0)),
                ('bankid_verified', models.BooleanField(default=False)),
                ('credit_score', models.FloatField(default=50.0)),
                ('has_debt_records', models.BooleanField(default=False)),
                ('preferred_districts', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Väntande'), ('qualified', 'Kvalificerad'), ('disqualified', 'Diskvalificerad'), ('selected', 'Utvald'), ('rejected', 'Avvisad'), ('withdrawn', 'Återkallad')], default='pending', max_length=20)),
                ('disqualification_reason', models.CharField(blank=True, max_length=300)),
                ('rank_score', models.FloatField(blank=True, null=True)),
                ('rank_position', models.PositiveIntegerField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Köplats',
                'verbose_name_plural': 'Köplatser',
                'ordering': ['-queue_points', 'applied_at'],
                'indexes': [models.Index(fields=['listing', 'status'], name='queue_queue_listing_80e5f4_idx'), models.Index(fields=['queue_points'], name='queue_queue_queue_p_d23fb8_idx')],
                'unique_together': {('listing', 'applicant_email')},
            },
        ),
    ]
