# Generated by Django 4.2.13 on 2026-03-23 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('org_number', models.CharField(help_text='Swedish org number format: XXXXXX-XXXX', max_length=20, unique=True)),
                ('website', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('county', models.CharField(default='Stockholm', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'municipalities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(default='Stockholm', max_length=100)),
                ('listing_type', models.CharField(choices=[('apartment', 'Lägenhet'), ('room', 'Rum'), ('house', 'Hus')], default='apartment', max_length=20)),
                ('rooms', models.PositiveSmallIntegerField()),
                ('size_sqm', models.PositiveIntegerField()),
                ('floor', models.SmallIntegerField(default=1)),
                ('total_floors', models.PositiveSmallIntegerField(default=5)),
                ('has_elevator', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('is_accessible', models.BooleanField(default=False)),
                ('allows_pets', models.BooleanField(default=False)),
                ('rent_sek', models.PositiveIntegerField(help_text='Monthly rent in SEK')),
                ('min_income_multiplier', models.FloatField(default=3.0, help_text='Applicant income must be at least this multiple of rent')),
                ('max_household_size', models.PositiveSmallIntegerField(default=6)),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('closed', 'Stängd'), ('coming_soon', 'Kommer snart')], default='active', max_length=20)),
                ('available_from', models.DateField()),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.landlord')),
                ('municipality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='listings.municipality')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['status', 'listing_type'], name='listings_li_status_7ee35b_idx'), models.Index(fields=['municipality', 'rent_sek'], name='listings_li_municip_6f3c5a_idx'), models.Index(fields=['rooms', 'size_sqm'], name='listings_li_rooms_439a49_idx')],
            },
        ),
    ]
