# Generated by Django 4.2.13 on 2026-03-23 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=200)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True, help_text='Personal message to the landlord')),
                ('monthly_income_sek', models.PositiveIntegerField()),
                ('household_size', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Utkast'), ('submitted', 'Inskickad'), ('under_review', 'Under granskning'), ('approved', 'Godkänd'), ('rejected', 'Avvisad'), ('withdrawn', 'Återkallad')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Ansökan',
                'verbose_name_plural': 'Ansökningar',
                'ordering': ['-submitted_at'],
                'unique_together': {('listing', 'applicant_email')},
            },
        ),
    ]
